### PR TITLE
Add support for chunked file uploads(Fog's default behavior)

### PR DESCRIPTION
**Pull request by simonoff**

### CODE REVIEW

**Comment by mdouchement** [comment]
Thanks! We will look at your PR ASAP

**Comment by mdouchement** [comment]
It seems to be a Rack/web-servers issue
- https://github.com/rails/rails/issues/15079
- https://github.com/macournoyer/thin/pull/71

If I understand these issues and `ChunkedTransferDecoder` middleware
- When we use Webrick or Unicorn/Rainbows/Zbatery, we have to setup to `true` the `decoded_upstream` option then the headers are changed.
- When we use Puma or Thin, we have to setup to `false` the `decoded_upstream` option then the headers are changed and the stream is decoded.


So in development environment with Webrick, we didn't need to decode the stream but in production with Puma we need to decode it. Can you handle this behavior in your PR ?

Can you put `chunked_transfer_decoder.rb` in `app/middleware` ?

**Comment by simonoff** [comment]
@mdouchement puma do not support chunked yet. I set it to false and all works fine with Webrick or Unicorn/Rainbows/Zbatery. With true it not working. At least for webrick and unicorn. Yes I can remove it to app/middleware

**Comment by mdouchement** [comment]
Ok, we can remove the useless code that do not fit to our case then the PR will be good.

I will replace Puma by Unicorn for production environment (Docker) in another PR.

**Comment by mdouchement** [comment]
Moved to https://github.com/PredicSis/s3-server/pull/24

**Pull request closed without merging**
